version: 2

multi-ecosystem-groups:
  infra:
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "infrastructure"

updates:
  - package-ecosystem: "npm"
    directory: "/ident"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
    groups:
      frontend:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/identd"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    groups:
      backend:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "infra"

  - package-ecosystem: "docker"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "infra"

  - package-ecosystem: "docker-compose"
    directory: "/packaging"
    patterns:
      - "*"
    multi-ecosystem-group: "infra"
